/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_meltzg_jmlm_device_MTPContentDevice_MTPDeviceInfo */

#ifndef _Included_org_meltzg_jmlm_device_MTPContentDevice_MTPDeviceInfo
#define _Included_org_meltzg_jmlm_device_MTPContentDevice_MTPDeviceInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
