language: java

jdk:
  - oraclejdk11

env:
  - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"

script:
  - ./gradlew check jacocoTestReport -PexcludeTests=**/MTP*

install: export CXX="g++-7"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

before_install:
  - sudo apt-get install jmtpfs -y

after_success:
  - bash <(curl -s https://codecov.io/bash)
